.PHONY: clean All

All:
	@echo "----------Building project:[ VariadictFunExample - Debug ]----------"
	@cd "VariadictFunExample" && "$(MAKE)" -f  "VariadictFunExample.mk"
clean:
	@echo "----------Cleaning project:[ VariadictFunExample - Debug ]----------"
	@cd "VariadictFunExample" && "$(MAKE)" -f  "VariadictFunExample.mk" clean
