.PHONY: clean All

All:
	@echo "----------Building project:[ MissingEle - Debug ]----------"
	@cd "MissingEle" && "$(MAKE)" -f  "MissingEle.mk"
clean:
	@echo "----------Cleaning project:[ MissingEle - Debug ]----------"
	@cd "MissingEle" && "$(MAKE)" -f  "MissingEle.mk" clean
