.PHONY: clean All

All:
	@echo "----------Building project:[ LinearHashing - Debug ]----------"
	@cd "LinearHashing" && "$(MAKE)" -f  "LinearHashing.mk"
clean:
	@echo "----------Cleaning project:[ LinearHashing - Debug ]----------"
	@cd "LinearHashing" && "$(MAKE)" -f  "LinearHashing.mk" clean
