.PHONY: clean All

All:
	@echo "----------Building project:[ DisplayLinkedList - Debug ]----------"
	@cd "DisplayLinkedList" && "$(MAKE)" -f  "DisplayLinkedList.mk"
clean:
	@echo "----------Cleaning project:[ DisplayLinkedList - Debug ]----------"
	@cd "DisplayLinkedList" && "$(MAKE)" -f  "DisplayLinkedList.mk" clean
